write_poem:
  description: >
    Write a poem about how CrewAI is awesome.
    Ensure the poem is engaging and adheres to the specified sentence count of {sentence_count}.
  expected_output: >
    A beautifully crafted poem and rap song about CrewAI, with exactly {sentence_count} sentences.
  agent: poem_writer
