[project]
name = "c1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chromadb>=0.5.23",
    "crewai>=0.95.0",
    "crewai-tools>=0.25.8",
    "pysqlite3-binary>=0.5.4",
    "rich>=13.9.4",
]
