[project]
name = "pro1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "crewai>=0.95.0",
    "crewai-tools>=0.25.8",
    "rich>=13.9.4",
]
